export enum OrderStatus {
  CREATED = 'CREATED',
  PICKING_PENDING = 'PICKING_PENDING',
  PICKING_IN_PROGRESS = 'PICKING_IN_PROGRESS',
  PICKED = 'PICKED',
  AUDIT_PENDING = 'AUDIT_PENDING',
  AUDIT_IN_PROGRESS = 'AUDIT_IN_PROGRESS',
  AUDIT_FAILED = 'AUDIT_FAILED',
  AUDIT_PASSED = 'AUDIT_PASSED',
  SHIPPING_PENDING = 'SHIPPING_PENDING',
  SHIPPING = 'SHIPPING',
  SHIPPED = 'SHIPPED',
  CLOSED = 'CLOSED',
}
