export enum ShipmentStatus {
  SCHEDULED = 'SCHEDULED',
  ARRIVED = 'ARRIVED',
  UNLOADING = 'UNLOADING',
  PUT_AWAY_PENDING = 'PUT_AWAY_PENDING',
  PUT_AWAY_IN_PROGRESS = 'PUT_AWAY_IN_PROGRESS',
  STORED = 'STORED',
  READY_TO_SHIP = 'READY_TO_SHIP',
  LOADING = 'LOADING',
  CLOSED = 'CLOSED',
}
